version: '3.1'
services:
  https-portal:
    # image: steveltn/https-portal:1
    build: ./https-portal/
    # ports:
    #   - '80:80'
    #   - '443:443'
    restart: always
    volumes:
      - ./https-portal/data/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: '${DOMAIN} -> http://rancher:80'
      STAGE: production
      # STAGE: local
      WEBSOCKET: 'true'
    depends_on:
      - rancher

  rancher:
    ports:
      - '80:80'
      - '443:443'
    image: rancher/rancher:latest
    volumes:
      - rancher_data:/var/lib/rancher
    restart: unless-stopped

volumes:
  rancher_data:
    driver: local
