version: '3.1'
services:
  https-portal:
    build: ./apps/https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./apps/https-portal/nginx-conf/domain.conf.erb:/var/lib/nginx-conf/${DOMAIN}.conf.erb:ro
      - ./apps/https-portal/nginx-conf/domain.ssl.conf.erb:/var/lib/nginx-conf/${DOMAIN}.ssl.conf.erb:ro
      - ./apps/https-portal/data/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: '${DOMAIN} -> http://rancher:80'
      STAGE: production
      WEBSOCKET: 'true'
    depends_on:
      - rancher

  rancher:
    image: rancher/rancher:latest
    volumes:
      - ./apps/rancher/data:/var/lib/rancher
    restart: always
