version: '3.1'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./https-portal/data/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: '${DOMAIN} -> http://rancher:80'
      STAGE: 'production'
      WEBSOCKET: 'true'
    depends_on:
      - rancher

  rancher:
    image: rancher/rancher:stable
    volumes:
      - mysql:/var/lib/mysql
      - mysql-log:/var/log/mysql
      - cattle:/var/log/cattle
    restart: unless-stopped

volumes:
  mysql:
  mysql-log:
  cattle:
