FROM steveltn/https-portal:1
ADD ./nginx-conf/domain.conf.erb /var/lib/nginx-conf/rancher.nontan18.xyz.conf.erb
ADD ./nginx-conf/domain.ssl.conf.erb /var/lib/nginx-conf/rancher.nontan18.xyz.ssl.conf.erb
